version: '3'

services:
  db:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - $PWD/sqls:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: upnid123
      MYSQL_USER: user
      MYSQL_PASSWORD: upnid123
      MYSQL_DATABASE: upnid_db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:mysql
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: upnid123